export const portfolioFront = [
  {
    title: "portfolio",
    imageType: "portfolio",
    videoId: "",
    videoBool: false,
    urlBool: false,
    url: "",
  },
  {
    title: "personalBlog",
    imageType: "personalblog",
    videoId: "3VB6-KLYQss",
    videoBool: true,
    urlBool: true,
    url: "https://www.blog.andrescazares.com/",
  },
  {
    title: "ASMPC",
    imageType: "asmpc",
    videoId: "lWhj9hW31Js",
    videoBool: true,
    urlBool: false,
    url: "",
  },
  {
    title: "CDC",
    imageType: "cdc",
    videoId: "x4eM3QJlwDE",
    videoBool: true,
    urlBool: false,
    url: "",
  },
  {
    title: "weather",
    imageType: "weather",
    videoId: "0gCM5yIAZ7Q",
    videoBool: true,
    urlBool: true,
    url: "https://www.clima.andrescazares.com",
  },
  {
    title: "taquero",
    imageType: "videogame",
    videoId: "g-3pOXJKiiE",
    videoBool: true,
    urlBool: false,
    url: "",
  },
];
export const portfolioBack = [
  {
    title: "strapiBlog",
    imageType: "strapi",
    videoId: "",
    videoBool: false,
    urlBool: true,
    url: "https://github.com/sayaskye/blog-strapi",
  },
];
export const portfolioCourses = [
  {
    title: "ProductHunt",
    imageType: "web",
    videoId: "",
    videoBool: false,
    urlBool: true,
    url: "https://www.phc.andrescazares.com",
  },
  {
    title: "chat",
    imageType: "chat",
    videoId: "D3u3pPRJStk",
    videoBool: true,
    urlBool: true,
    url: "https://www.superchat.andrescazares.com",
  },
  {
    title: "blogphp",
    imageType: "phpblog",
    videoId: "dpMQ3WPNOqE",
    videoBool: true,
    urlBool: false,
    url: "",
  },
  {
    title: "apiLaravel",
    imageType: "apis",
    videoId: "",
    videoBool: false,
    urlBool: true,
    url: "https://github.com/sayaskye/apirestlaravel",
  },
  {
    title: "apiNode",
    imageType: "apis",
    videoId: "",
    videoBool: false,
    urlBool: true,
    url: "https://github.com/sayaskye/apirestnodejs",
  },
];
